[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "slurm-venturer"
version = "1.0"
readme = "README.md"
dependencies = [
    "pandas",
    "matplotlib",
    "typer",
]
[project.scripts]
slurm-venturer = "slurm_venturer.cli:app"
[tool.hatch.build.targets.wheel]
packages = ["src/slurm_venturer"]